### ISSUE TITLE
Help:how to

### ISSUE THREAD

**Issue by amitmjosbi** [mwicat/skinnygen#1]
Hi,
Please add how to use this within python framework.
Is it a standalone utility?

thanks
--amit

**Comment by dkgroot** [comment]
Hi Amit,

What python framework are you refering to ?

Yes it is a standalone utility, see the readme:
usage: skinnygen generate [-h] [--host HOST] [--port PORT]
                          [--user_handler USER_HANDLER]
                          [--call_handler CALL_HANDLER] [--numbers NUMBERS]
                          [--numbers_file NUMBERS_FILE]
                          device self_line

What issue are you running into.

Do note that this application has not been updated for a while. Some of the messages sent/handles might be somewhat out of date.

**Comment by ajoshilabs** [comment]
Thanks for your reply.
I was trying it as standalone and even under python but seems not working for me.

root@client:/home/amit# skinnygen generate -h
Traceback (most recent call last):
  File "/usr/local/bin/skinnygen", line 9, in <module>
    load_entry_point('skinnygen==0.0.1', 'console_scripts', 'skinnygen')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2361, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
ImportError: No module named skinnygen

**Comment by mwicat** [comment]
@amitmjosbi I will try to update it as soon as I can

**Comment by mwicat** [comment]
@amitmjosbi I managed it to run, yet I don't have environment to test it with server. Please try with this:

sudo apt-get install python python-pip python-twisted
sudo pip install -e git+git://github.com/mwicat/sccp.git#egg=sccp
sudo pip install -e git+git://github.com/mwicat/skinnygen.git#egg=skinnygen
